version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9090"

  app:
    image: kotekaman:duckdelta-testing
    container_name: my-app
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: secret123
    depends_on:
      - minio
